<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <text style="color: red; font-size: 500px; margin-top: 50%;margin-bottom: 50%;"><b>404</b></text>
        </div>
        <div class="col-md-4">
            <p style="font-size: 28px; margin-top: 95%;"><b>Ups! Pagina nao encontrada</b></p>
            <p style="font-size: 30px;">Recomendamos que volte a pagina inicial e pode reportar o erro.</p>
        </div>
    </div>
</div>