
      <div class="container">
       <div class="row">
        <div class="col-sm-6">
          <h2>Aplicação da lei de violência doméstica em Moçambique: constrangimentos institucionais e culturais
          A experiência dos Tribunais
          José Alfredo Macaringue</h2>

          <br>

          <h4>(Juiz de Direito – Tribunal J.D.M. KaMubukwana – Maputo)
                Publicado em “Outras Vozes”, nº 41-42, Maio 2013</h4>

                <br>

          <h5>Considerações gerais</h5>

          A violência doméstica é um dos mais graves problemas que a sociedade contemporânea enfrenta. É uma forma de violência que não conhece fronteiras, nem obedece a princípios ou leis. Ocorre diariamente em Moçambique e noutros países, apesar de existir um quadro constitucional e legal que veio introduzir vários mecanismos de protecção dos direitos humanos, em especial de protecção dos direitos da mulher e da criança.
          Não obstante a Constituição da República ter consagrado como alguns dos princípios fundamentais do Estado moçambicano (cfr. Artigos 3 e 11, alínea e) C.R.M.), “o respeito e garantia dos direitos e liberdades fundamentais do Homem; a defesa e a promoção dos direitos humanos e da igualdade dos cidadãos perante a lei e, como direito fundamental, a igualdade de género”, ao plasmar no artigo 36, a igualdade do homem e da mulher perante a lei, em todos os domínios da vida política, económica, social e cultural, o direito penal e o direito processual penal ainda se preocupam, em grande medida, com o crime e com o criminoso, deixando de lado quem mais necessita de assistência e apoio: a vítima.

        
    	</div>
        <div class="col-sm-6">
          <h3>Texto da Lei nº 29/2009, sobre a Violência Doméstica praticada contra a Mulher. </h3>

          <!-----------------PDF-------------------------->
                    <div>

                            <p>Baixe o Texto da Lei nº 29/2009</p>

                            <a href="doc/Lei_VD_2009.pdf"><div class="icon-file"><button class="btn btn-warning"><i class="fa fa-download" aria-hidden="true"></i> Clique aqui</button></div></a>
                    </div>
                    
                    <!-----------------PDF-------------------------->

          <link rel="stylesheet" type="text/css" href="">
     </div>
      </div>
      
      </div>